apiVersion: v1
kind: ConfigMap
metadata:
  name: sing-box-noauth-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    log:
      level: {{ .Values.singBox.log.level }}
      timestamp: {{ .Values.singBox.log.timestamp }}
    inbounds:
      - type: http
        tag: http-in-noauth
        listen: 0.0.0.0
        listen_port: 3128
      - type: socks
        tag: socks-in-noauth
        listen: 0.0.0.0
        listen_port: 1080
    outbounds:
      - type: direct
        tag: direct
    route:
      rules:
        - inbound:
            - http-in-noauth
            - socks-in-noauth
          outbound: direct
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sing-box-auth-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    log:
      level: {{ .Values.singBox.log.level }}
      timestamp: {{ .Values.singBox.log.timestamp }}
    inbounds:
      - type: http
        tag: http-in-auth
        listen: 0.0.0.0
        listen_port: 3128
        users:
          - username: {{ .Values.singBox.auth.username }}
            password: {{ .Values.singBox.auth.password }}
      - type: socks
        tag: socks-in-auth
        listen: 0.0.0.0
        listen_port: 1080
        users:
          - username: {{ .Values.singBox.auth.username }}
            password: {{ .Values.singBox.auth.password }}
    outbounds:
      - type: direct
        tag: direct
    route:
      rules:
        - inbound:
            - http-in-auth
            - socks-in-auth
          outbound: direct