apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-noauth
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-noauth
  template:
    metadata:
      labels:
        app: http-noauth
    spec:
      containers:
        - name: http-noauth
          image: "{{ .Values.singBox.image.repository }}:{{ .Values.singBox.image.tag }}"
          imagePullPolicy: {{ .Values.singBox.image.pullPolicy }}
          ports:
            - containerPort: 3128
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/sing-box/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.singBox.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: sing-box-noauth-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-noauth
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks-noauth
  template:
    metadata:
      labels:
        app: socks-noauth
    spec:
      containers:
        - name: socks-noauth
          image: "{{ .Values.singBox.image.repository }}:{{ .Values.singBox.image.tag }}"
          imagePullPolicy: {{ .Values.singBox.image.pullPolicy }}
          ports:
            - containerPort: 1080
              name: socks
          volumeMounts:
            - name: config
              mountPath: /etc/sing-box/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.singBox.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: sing-box-noauth-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-auth
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-auth
  template:
    metadata:
      labels:
        app: http-auth
    spec:
      containers:
        - name: http-auth
          image: "{{ .Values.singBox.image.repository }}:{{ .Values.singBox.image.tag }}"
          imagePullPolicy: {{ .Values.singBox.image.pullPolicy }}
          ports:
            - containerPort: 3128
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/sing-box/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.singBox.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: sing-box-auth-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-auth
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks-auth
  template:
    metadata:
      labels:
        app: socks-auth
    spec:
      containers:
        - name: socks-auth
          image: "{{ .Values.singBox.image.repository }}:{{ .Values.singBox.image.tag }}"
          imagePullPolicy: {{ .Values.singBox.image.pullPolicy }}
          ports:
            - containerPort: 1080
              name: socks
          volumeMounts:
            - name: config
              mountPath: /etc/sing-box/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.singBox.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: sing-box-auth-config