apiVersion: v1
kind: Service
metadata:
  name: http-noauth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.httpNoauth.service.type }}
  ports:
    - port: {{ .Values.httpNoauth.service.port }}
      targetPort: 3128
      protocol: TCP
      name: http
  selector:
    app: http-noauth
---
apiVersion: v1
kind: Service
metadata:
  name: socks-noauth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.socksNoauth.service.type }}
  ports:
    - port: {{ .Values.socksNoauth.service.port }}
      targetPort: 1080
      protocol: TCP
      name: socks
  selector:
    app: socks-noauth
---
apiVersion: v1
kind: Service
metadata:
  name: http-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.httpAuth.service.type }}
  ports:
    - port: {{ .Values.httpAuth.service.port }}
      targetPort: 3128
      protocol: TCP
      name: http
  selector:
    app: http-auth
---
apiVersion: v1
kind: Service
metadata:
  name: socks-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.socksAuth.service.type }}
  ports:
    - port: {{ .Values.socksAuth.service.port }}
      targetPort: 1080
      protocol: TCP
      name: socks
  selector:
    app: socks-auth