apiVersion: v1
kind: Service
metadata:
  name: squid-noauth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.squidNoauth.service.type }}
  ports:
    - port: {{ .Values.squidNoauth.service.port }}
      targetPort: 3128
      protocol: TCP
  selector:
    app: squid-noauth
---
apiVersion: v1
kind: Service
metadata:
  name: dante-noauth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.danteNoauth.service.type }}
  ports:
    - port: {{ .Values.danteNoauth.service.port }}
      targetPort: 1080
      protocol: TCP
  selector:
    app: dante-noauth
---
apiVersion: v1
kind: Service
metadata:
  name: squid-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.squidAuth.service.type }}
  ports:
    - port: {{ .Values.squidAuth.service.port }}
      targetPort: 3128
      protocol: TCP
  selector:
    app: squid-auth
---
apiVersion: v1
kind: Service
metadata:
  name: dante-auth
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.danteAuth.service.type }}
  ports:
    - port: {{ .Values.danteAuth.service.port }}
      targetPort: 1080
      protocol: TCP
  selector:
    app: dante-auth
