singBox:
  image:
    repository: ghcr.io/sagernet/sing-box
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  log:
    level: info
    timestamp: true
  auth:
    enabled: true
    username: proxy_user
    password: "55688"

httpNoauth:
  service:
    type: ClusterIP
    port: 3128

socksNoauth:
  service:
    type: ClusterIP
    port: 1080

httpAuth:
  service:
    type: ClusterIP
    port: 3128

socksAuth:
  service:
    type: ClusterIP
    port: 1080
