squidNoauth:
  image:
    repository: ubuntu/squid
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3128
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

danteNoauth:
  image:
    repository: vimagick/dante
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 1080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

squidAuth:
  image:
    repository: ubuntu/squid
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3128
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

danteAuth:
  image:
    repository: vimagick/dante
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 1080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
